name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Test
        run: |
          # Create .env file for CI environment
          echo "ENVIRONMENT=CI" > .env
          echo "LOG_IGNORED_LEXEMES=true" >> .env
          echo "LOGGING_LEVEL=ALL" >> .env
          echo "PULL_POLICY=if_not_present" >> .env

          # Run build script
          docker compose run --rm compiler ./src/main/bash/build.sh
          
          # Run tests
          docker compose run --rm compiler ./src/main/bash/test.sh
